// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT386LFR4DLYlEQYRc_D87QrG73AygZ0Q',
    appId: '1:637062336980:web:e6d585a489642442cfc641',
    messagingSenderId: '637062336980',
    projectId: 'wajibika-app',
    authDomain: 'wajibika-app.firebaseapp.com',
    storageBucket: 'wajibika-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHxCIJzPKzR1YnZNIXreGUliefaL2S-BI',
    appId: '1:637062336980:android:6019cd1f9a827975cfc641',
    messagingSenderId: '637062336980',
    projectId: 'wajibika-app',
    storageBucket: 'wajibika-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcTIuRTFd8LixKoUMYQiN8YwkisjgNMSQ',
    appId: '1:637062336980:ios:6cbe5b44fddbf3e4cfc641',
    messagingSenderId: '637062336980',
    projectId: 'wajibika-app',
    storageBucket: 'wajibika-app.firebasestorage.app',
    iosBundleId: 'com.example.wajibikaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcTIuRTFd8LixKoUMYQiN8YwkisjgNMSQ',
    appId: '1:637062336980:ios:6cbe5b44fddbf3e4cfc641',
    messagingSenderId: '637062336980',
    projectId: 'wajibika-app',
    storageBucket: 'wajibika-app.firebasestorage.app',
    iosBundleId: 'com.example.wajibikaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT386LFR4DLYlEQYRc_D87QrG73AygZ0Q',
    appId: '1:637062336980:web:2e19b7aab9249d3fcfc641',
    messagingSenderId: '637062336980',
    projectId: 'wajibika-app',
    authDomain: 'wajibika-app.firebaseapp.com',
    storageBucket: 'wajibika-app.firebasestorage.app',
  );
}
